database:
  user: postgres
  password: 2020
  host: host.docker.internal
  port: 5432
  dbname: crash_auth
  sslmode: disable

server:
  host: "0.0.0.0"
  port: ":9000"
  write_timeout: 15s
  read_timeout: 15s

billing_client:
  host: localhost
  port: 9001

currency_client:
  host: localhost
  port: 9002

jwt:
  secret_key: "my_secret_key228"
  token_lifetime: "24h"

logger:
  encoding: json
  level: info
  outputPaths:
    - stdout
  errorOutputPaths:
    - stderr

metrics:
  path: "/metrics"